"""
Retrieval Agent — the first node in the orchestration pipeline.

Given a patient_id, retrieves structured, categorized chart context from
the vector store: several targeted searches across clinically-motivated
categories, each patient-scoped and relevance-thresholded (see
src/retrieval/query_store.py).

Categories can be FIXED (5 generic ones, no LLM dependency, always
available) or DYNAMIC (generated by an LLM from this patient's actual
admission reason and risk assessment — see generate_dynamic_categories).
Dynamic generation falls back to the fixed set on any failure, so
retrieval never comes up empty just because an LLM call had a bad day.

A category with no relevant match is tracked explicitly, not silently
dropped — "no documented follow-up plan found" is itself useful signal
for the reasoning agent (and eventually the clinician), not a gap to
paper over.
"""

import json
import logging
import sys
from dataclasses import dataclass, field

sys.path.insert(0, ".")
from src.retrieval.query_store import get_collection, retrieve_relevant_context
from src.utils.runtime import LLM_TIMEOUT_SECONDS

logger = logging.getLogger(__name__)

RETRIEVAL_CATEGORIES = {
    "admission_reason": "chief complaint and reason for hospitalization",
    "comorbidities": "chronic conditions and comorbidities in patient history",
    "medications": "current medications at discharge",
    "procedures_and_plan": "procedures conducted and treatment plan during this admission",
    "follow_up": "follow-up care instructions and discharge planning",
}

DYNAMIC_QUERY_SYSTEM_PROMPT = """You generate targeted search queries for a clinical chart retrieval system, given a patient's admission reason and risk assessment.

Given the context below, produce 4-6 specific search queries that would surface the most clinically relevant documentation for THIS patient's situation — tailored to their actual admission reason, not a generic checklist.

Respond with ONLY a JSON object, no other text, in this exact format:
{"category_label": "search query text", "another_category_label": "another search query text"}

Category labels should be short (2-4 words, readable as a section header). Query text should be a natural-language description of what to search for, e.g. "chronic conditions and comorbidities in patient history"."""


def generate_dynamic_categories(admission_reason: str, risk_info: dict | None = None, groq_model: str | None = None) -> dict[str, str]:
    """
    Uses an LLM to generate search categories/queries tailored to this
    patient's actual admission reason, instead of the fixed 5 generic
    ones. Falls back to RETRIEVAL_CATEGORIES on ANY failure — logged as
    a warning, not raised, since falling back to known-good fixed
    categories is always a reasonable outcome here.
    """
    import os

    from groq import Groq

    api_key = os.getenv("GROQ_API_KEY")
    if not api_key:
        logger.warning("GROQ_API_KEY not set — falling back to fixed RETRIEVAL_CATEGORIES")
        return RETRIEVAL_CATEGORIES

    model = groq_model or os.getenv("GROQ_MODEL", "openai/gpt-oss-120b")
    context_line = f"Admission reason: {admission_reason}"
    if risk_info:
        context_line += f"\nRisk category: {risk_info.get('risk_category', 'unknown')}"

    try:
        client = Groq(api_key=api_key, timeout=LLM_TIMEOUT_SECONDS)
        response = client.chat.completions.create(
            model=model,
            messages=[
                {"role": "system", "content": DYNAMIC_QUERY_SYSTEM_PROMPT},
                {"role": "user", "content": context_line},
            ],
            temperature=0.3,
        )
        raw = response.choices[0].message.content.strip()
        if raw.startswith("```"):
            raw = raw.split("```")[1]
            if raw.startswith("json"):
                raw = raw[4:]
        categories = json.loads(raw.strip())

        if not isinstance(categories, dict) or not (2 <= len(categories) <= 8):
            raise ValueError(f"Unexpected shape: {type(categories)}")
        if not all(isinstance(k, str) and isinstance(v, str) for k, v in categories.items()):
            raise ValueError("Categories must be a flat dict of str -> str")

        logger.info("Generated %d dynamic retrieval categories for admission_reason=%r", len(categories), admission_reason)
        return categories

    except Exception as e:
        logger.warning("Dynamic category generation failed (%s) — falling back to fixed RETRIEVAL_CATEGORIES", e)
        return RETRIEVAL_CATEGORIES


@dataclass
class RetrievedItem:
    category: str
    section: str
    text: str
    distance: float
    encounter_id: str


@dataclass
class PatientContext:
    patient_id: str
    categories_used: dict[str, str] = field(default_factory=dict)
    items: list[RetrievedItem] = field(default_factory=list)
    categories_with_no_match: list[str] = field(default_factory=list)

    def summary_text(self) -> str:
        """
        Uses THIS context's own categories_used, not a module-level
        constant, so it renders correctly whether the categories were
        fixed or dynamically generated for this specific patient.
        """
        lines = [f"Chart context for patient {self.patient_id}:\n"]
        by_category: dict[str, list[RetrievedItem]] = {}
        for item in self.items:
            by_category.setdefault(item.category, []).append(item)

        for category, label in self.categories_used.items():
            lines.append(f"## {label.capitalize()}")
            if category in by_category:
                for item in by_category[category]:
                    lines.append(f"- [{item.section}, distance={item.distance:.3f}] {item.text}")
            else:
                lines.append("(no relevant documentation found)")
            lines.append("")

        return "\n".join(lines)


def retrieve_patient_context(
    patient_id: str,
    collection=None,
    n_results_per_category: int = 2,
    categories: dict[str, str] | None = None,
) -> PatientContext:
    """
    categories=None uses the fixed RETRIEVAL_CATEGORIES (unchanged
    default behavior). Pass a dict (e.g. from generate_dynamic_categories)
    to use dynamic ones instead.
    """
    collection = collection or get_collection()
    categories = categories or RETRIEVAL_CATEGORIES
    context = PatientContext(patient_id=patient_id, categories_used=categories)

    for category, query_text in categories.items():
        results = retrieve_relevant_context(collection, patient_id, query_text, n_results=n_results_per_category)
        if results is None:
            context.categories_with_no_match.append(category)
            continue
        for r in results:
            context.items.append(RetrievedItem(
                category=category,
                section=r["section"],
                text=r["text"],
                distance=r["distance"],
                encounter_id=r["encounter_id"],
            ))

    return context


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python3 -m src.agents.retrieval_agent <patient_id> [--dynamic]")
        sys.exit(1)

    patient_id = sys.argv[1]
    use_dynamic = "--dynamic" in sys.argv

    cats = None
    if use_dynamic:
        cats = generate_dynamic_categories(admission_reason="unknown (standalone test)")

    context = retrieve_patient_context(patient_id, categories=cats)
    print(context.summary_text())
    if context.categories_with_no_match:
        print(f"Categories with no documented match: {context.categories_with_no_match}")
